### ISSUE TITLE
how to get the best solution

### ISSUE THREAD

**Issue by jermaine1ronquillo** [tsyet12/Moptimal#5]
Particle Swarm Optimization has pso.global_best_domain, how about the other algorithms?

**Comment by tsyet12** [comment]
You can use [solver object].bestdomain or [solver object].bestresults. I apologize that the syntax for this function is not very unified for each solver. I will update it later and let you know.

**Comment by jermaine1ronquillo** [comment]
Thank you fornthe reply, bestdomain and bestresults gave me a list of values

**Comment by tsyet12** [comment]
FYI. Add [-1] to get the last value. For example [solver object].bestdomain[-1].

**Comment by jermaine1ronquillo** [comment]
Thank you

**Comment by jermaine1ronquillo** [comment]
pso.global_best_domain has different value compared to pso.best_domain[-1]

**Comment by jermaine1ronquillo** [comment]
duelist algorithm doesn't have [solver object].bestdomain[-1],but hasl_bestdomain
